#!/usr/bin/env bash
# why
pi="/var/run/myscript.pid"
echo $$ > "$pi"
trap 'echo "I hate the kill command"; rm -f "$pi"; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pi"; exit' SIGQUIT
while :; do
    echo "To infinity and beyond"
    sleep 2
done
