#!/usr/bin/env bash
# manager
pi="/var/run/my_process.pid"

start() {
    ./manage_my_process &        # run in background
    echo $! > "$PIDFILE"         # save PID
    echo "manage_my_process started"
}
stop() {
    [ -f "$pi" ] && kill $(cat "$pi") 2>/dev/null
    rm -f "$pi"
    echo "manage_my_process stopped"
}
restart() {
    stop
    start
    echo "manage_my_process restarted"
}
case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    *) echo "Usage: manage_my_process {start|stop|restart}" ;;
esac
